# Generated by Django 3.2 on 2021-05-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210507_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
    ]
