# Generated by Django 3.2 on 2021-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210507_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='staff',
        ),
        migrations.AddField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
