# Generated by Django 3.2 on 2021-05-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='cover_art',
            new_name='img',
        ),
    ]
