// ui stuff
export const SWITCH_NAV_BG_COLOR = "SWITCH_NAV_BG_COLOR";
export const SWITCH_HERO_PRESENCE = "SWITCH_HERO_PRESENCE";
export const SWITCH_HERO_VISIBILITY = "SWITCH_HERO_VISIBILITY";

export const SWITCH_NAV_BG_SOLID = "SWITCH_NAV_BG_SOLID";
export const SWITCH_NAV_BG_TRANSPARENT = "SWITCH_NAV_BG_TRANSPARENT";

export const SET_VOTING_SECTION_IN_VIEW = "SET_VOTING_SECTION_IN_VIEW";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Auth stuff
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";

export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";

export const LOGOUT = "LOGOUT";

// Blog Stuff
export const FETCH_LATEST_POSTS = "FETCH_LATEST_POSTS";
export const FETCH_LATEST_POSTS_FAIL = "FETCH_LATEST_POSTS_FAIL";

export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";

// Categories Stuff
export const SET_TOTAL_SONG_CATEGORIES = "SET_TOTAL_SONG_CATEGORIES";
export const SET_TOTAL_MOVIE_CATEGORIES = "SET_TOTAL_MOVIE_CATEGORIES";
export const SET_TOTAL_ARTIST_CATEGORIES = "SET_TOTAL_ARTIST_CATEGORIES";

export const FETCH_ALL_MOVIE_CATEGORIES_SUCCESS =
  "FETCH_ALL_MOVIE_CATEGORIES_SUCCESS";
export const FETCH_ALL_MOVIE_CATEGORIES_FAIL =
  "FETCH_ALL_MOVIE_CATEGORIES_FAIL";

export const FETCH_ALL_SONG_CATEGORIES_SUCCESS =
  "FETCH_ALL_SONG_CATEGORIES_SUCCESS";
export const FETCH_ALL_SONG_CATEGORIES_FAIL = "FETCH_ALL_SONG_CATEGORY_FAIL";

export const FETCH_ALL_ARTIST_CATEGORIES_SUCCESS =
  "FETCH_ALL_ARTIST_CATEGORIES_SUCCESS";
export const FETCH_ALL_ARTIST_CATEGORIES_FAIL =
  "FETCH_ALL_ARTIST_CATEGORY_FAIL";

// Voting stuff
export const CAST_VOTE_IN_CATEGORY_SUCCESS = "CAST_VOTE_IN_CATEGORY_SUCCESS";
export const CAST_VOTE_IN_CATEGORY_FAIL = "CAST_VOTE_IN_CATEGORY_FAIL";
export const SET_CHOICE_IN_CAT = "SET_CHOICE_IN_CAT";

export const SET_CURRENT_MOVIE_CATEGORY = "SET_CURRENT_MOVIE_CATEGORY";
export const SET_CURRENT_SONG_CATEGORY = "SET_CURRENT_SONG_CATEGORY";
export const SET_CURRENT_ARTIST_CATEGORY = "SET_CURRENT_ARTIST_CATEGORY";

export const SET_PREV_MOVIE_CATEGORY = "SET_PREV_MOVIE_CATEGORY";
export const SET_PREV_SONG_CATEGORY = "SET_PREV_SONG_CATEGORY";
export const SET_PREV_ARTIST_CATEGORY = "SET_PREV_ARTIST_CATEGORY";

export const SET_NEXT_MOVIE_CATEGORY = "SET_NEXT_MOVIE_CATEGORY";
export const SET_NEXT_SONG_CATEGORY = "SET_NEXT_SONG_CATEGORY";
export const SET_NEXT_ARTIST_CATEGORY = "SET_NEXT_ARTIST_CATEGORY";
