// Ui stuff
export const SWITCH_NAV_BG_COLOR = "SWITCH_NAV_BG_COLOR";
export const SWITCH_HERO_PRESENCE = "SWITCH_HERO_PRESENCE";
export const SWITCH_HERO_VISIBILITY = "SWITCH_HERO_VISIBILITY";

export const SWITCH_NAV_BG_SOLID = "SWITCH_NAV_BG_SOLID";
export const SWITCH_NAV_BG_TRANSPARENT = "SWITCH_NAV_BG_TRANSPARENT";

// Auth stuff
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";

export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";

export const LOGOUT = "LOGOUT";

// Blog Stuff
export const FETCH_LATEST_POSTS = "FETCH_LATEST_POSTS";
export const FETCH_LATEST_POSTS_FAIL = "FETCH_LATEST_POSTS_FAIL";
