# Generated by Django 3.2 on 2021-05-07 05:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210507_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
