# Generated by Django 3.2 on 2021-05-11 04:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210507_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
