# Generated by Django 3.2 on 2021-06-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210609_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo_thumb',
            new_name='main_photo_thumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_2',
        ),
    ]
